# Generated by Django 2.1.3 on 2018-11-10 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoginUser',
            new_name='User',
        ),
    ]
